import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sibebar from "./ui/Sibebar";

const inter = Inter({ subsets: ["latin"],  });

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="max-h-screen md:flex overflow-hidden p-2 bg-white text-xs">
          <div className=" md:w-64 md:min-h-screen border overflow-hidden">
          <Sibebar/>
          </div>
          <div className="w-full h-screen hover:overflow-auto">
          {children}
          </div>
        </main>
      </body>
    </html>
  );
}
